// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhkZtsn06MoJ4CKUkduqSCzlniZes5ptI',
    appId: '1:726492729658:web:f41f58b3757987a7adc003',
    messagingSenderId: '726492729658',
    projectId: 'personalnotesapp-983eb',
    authDomain: 'personalnotesapp-983eb.firebaseapp.com',
    storageBucket: 'personalnotesapp-983eb.appspot.com',
    measurementId: 'G-T35GM2XVRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuoZQ0TZm9aNJzwZo-8ejmCsCIJVaqG30',
    appId: '1:726492729658:android:2d2f84b84e3bfbe2adc003',
    messagingSenderId: '726492729658',
    projectId: 'personalnotesapp-983eb',
    storageBucket: 'personalnotesapp-983eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkq9b9fYvWbAoC6JatQFCLgcCI_RhGjK8',
    appId: '1:726492729658:ios:cc70fecaed1f4632adc003',
    messagingSenderId: '726492729658',
    projectId: 'personalnotesapp-983eb',
    storageBucket: 'personalnotesapp-983eb.appspot.com',
    iosClientId: '726492729658-ce601c36iiub0f9dandouqkadg9aiu39.apps.googleusercontent.com',
    iosBundleId: 'com.reflieHer.personalnotesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkq9b9fYvWbAoC6JatQFCLgcCI_RhGjK8',
    appId: '1:726492729658:ios:cc70fecaed1f4632adc003',
    messagingSenderId: '726492729658',
    projectId: 'personalnotesapp-983eb',
    storageBucket: 'personalnotesapp-983eb.appspot.com',
    iosClientId: '726492729658-ce601c36iiub0f9dandouqkadg9aiu39.apps.googleusercontent.com',
    iosBundleId: 'com.reflieHer.personalnotesapp',
  );
}
